---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "leviosam2_index"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::leviosam2=0.4.2"
